services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./config/:/mosquitto/config/:ro
      - ./log/:/mosquito/log/
      - ./data:/mosquito/data/
    ports:
      - 1883:1883 #mqtt
      - 9001:9001 #ws
    restart: unless-stopped

volumes:
  data: ~
